package wacc.backend.midir

object LowerToTacConstant {
  val SC_LABEL_PREFIX_AND = "and"
  val SC_LABEL_PREFIX_OR  = "or"
  val IF_LABEL_ELSE = "if_else"
  val IF_LABEL_END  = "if_end"
  val WHILE_LABEL_HEAD = "while_head"
  val WHILE_LABEL_END  = "while_end"
  val SC_LABEL_SUFFIX_BRANCH = "_branch"
  val SC_LABEL_SUFFIX_END    = "_end"
  val ERR_UNDEFINED_VAR_PREFIX = "Undefined variable: "
  val ERR_INVALID_READ_TYPE = "Invalid read type"
  val ERR_FREE_STRING_ILLEGAL = "free string should be rejected by frontend"
  val ERR_FREE_UNSUPPORTED_PREFIX = "free only supports array/pair, got "
  val ERR_FREE_EXPR_UNIMPLEMENTED_PREFIX = "Free expr not implemented yet: "
  val ERR_FRONTEND_UNKNOWN_TYPE = "Frontend gave unknown type!"
  val ERR_REQUIRE_ARRAY = "require an array"
  val ERR_ARRAYELEM_EMPTY_INDICES = "ArrayElem with empty indices"
  val ERR_BREAK_OUTSIDE_LOOP = "break encountered without an active loop"
  val ERR_CONTINUE_OUTSIDE_LOOP = "continue encountered without an active loop"
  val ERR_PRINT_EXCEPTION = "invalid print of an exception"
  val CATCH_DISPATCH = "catch_dispatch"
  val TRY_END = "try_end"
  val NEXT_HANDLER = "next_handler"
  val HANDLER_MATCH = "handler_match"
  val NO_EXCEPTION = "no_exception"
  val RUNTIME_CHECK_OK = "runtime_check_ok"
  val RUNTIME_CHECK_OVERFLOW = "runtime_check_overflow"
  val RUNTIME_CHECK_END = "runtime_check_end"
  val ERR_DIVIDE_BY_ZERO = "divide or modulo by zero"
  val ERR_INTEGER_OVERFLOW = "integer overflow or underflow occurred"
  val ERR_BAD_CHAR_RANGE = "int is not ascii character 0-127"
  val ERR_NULL_DEREFERENCE_RUNTIME = "null dereference or freed pair"
  val ERR_ARRAY_INDEX_OUT_OF_BOUNDS = "array index out of bounds"
}
